# NUMPY

## Exercise 1

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [12]:
print("NumPy version:", np.__version__)

NumPy version: 1.26.4


## Homework 1

### Research and explain the difference between NumPy arrays and Python lists.

Performance: NumPy arrays are faster and consume less memory than Python lists due to efficient memory storage and vectorized operations.

Functionality: NumPy provides advanced mathematical operations, broadcasting, and multi-dimensional array handling, which lists lack.

Type Consistency: NumPy arrays store elements of the same type, whereas lists can contain mixed data types.

### Write a script that checks if NumPy is installed and prints an appropriate message.

In [59]:
try:
    import numpy as np
    print("NumPy is installed.")
except ImportError:
    print("NumPy is not installed. Install it using 'pip install numpy'.")

NumPy is installed.


## Creating Numpy Arrays

In [16]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [24]:
np.zeros((3,3))      

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2,2))       

array([[1., 1.],
       [1., 1.]])

In [22]:
np.arange(0,10,2)   

array([0, 2, 4, 6, 8])

In [26]:
np.linspace(0,10,5)  

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Exercise 2

### 1. Create a 1D NumPy array with values from 10 to 50.

In [37]:
array_1d = np.arange(10, 51)
print("1D Array:", array_1d)

1D Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


### 2. Create a 4x4 array filled with random values.

In [39]:
array_4x4 = np.random.rand(4, 4)
print("\n4x4 Random Array:\n", array_4x4)


4x4 Random Array:
 [[0.62645466 0.63529705 0.94216758 0.76723188]
 [0.585634   0.43343963 0.73233222 0.35385672]
 [0.1598286  0.22737937 0.10288698 0.5136041 ]
 [0.41916709 0.88558878 0.33538456 0.44673688]]


### 3. Generate an array with 15 values evenly spaced between 1 and 100.

In [41]:
array_spaced = np.linspace(1, 100, 15)
print("\nEvenly Spaced Array:", array_spaced)


Evenly Spaced Array: [  1.           8.07142857  15.14285714  22.21428571  29.28571429
  36.35714286  43.42857143  50.5         57.57142857  64.64285714
  71.71428571  78.78571429  85.85714286  92.92857143 100.        ]


## Homework 2

### Write a Python function that creates a NumPy array of size n filled with random integers.

In [48]:
def random_integer_array(n, low=0, high=100):
    return np.random.randint(low, high, size=n)

random_array = random_integer_array(10)  # Generating an array of 10 random integers
print("Random Integer Array:", random_array)

Random Integer Array: [ 8 41 51 17 97 77 70 95 66 27]


### Implement a script that generates a 5x5 identity matrix using NumPy.

In [50]:
identity_matrix = np.eye(5)
print("\n5x5 Identity Matrix:\n", identity_matrix)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Accessing Elements

In [62]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   # First element
print(arr[-1])  # Last element

10
50


## Slicing

In [64]:
arr = np.array([0, 10, 20, 30, 40, 50])
print(arr[1:4])  # Elements from index 1 to 3

[10 20 30]


## Exercise 3

### Create a 5x5 matrix of integers from 1 to 25 and extract: 
### The first row
### The last column
### A 3x3 sub-matrix from the center


In [75]:
matrix = np.arange(1, 26).reshape(5, 5)

first_row = matrix[0, :]

last_column = matrix[:, -1]

center_submatrix = matrix[1:4, 1:4]

print("5x5 Matrix:\n", matrix)
print("\nFirst Row:", first_row)
print("\nLast Column:\n", last_column)
print("\n3x3 Center Sub-matrix:\n", center_submatrix)

5x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First Row: [1 2 3 4 5]

Last Column:
 [ 5 10 15 20 25]

3x3 Center Sub-matrix:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


## Homework 3

### Implement a script that reverses a NumPy array.

In [81]:
def reverse_array(arr):
    return arr[::-1]
    
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
reversed_array = reverse_array(array)

print("Original Array:", array)
print("Reversed Array:", reversed_array)

Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Reversed Array: [10  9  8  7  6  5  4  3  2  1]


### Write a Python function that extracts every alternate element from a NumPy array.

In [83]:
def alternate_elements(arr):
    return arr[::2]

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
alternate_array = alternate_elements(array)

print("Alternate Elements:", alternate_array)

Alternate Elements: [1 3 5 7 9]


## Reshaping

In [86]:
arr = np.arange(1, 10)
reshaped = arr.reshape(3, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Concatenation

In [91]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
np.vstack((arr1, arr2))   # Vertical stack
np.hstack((arr1, arr2.T)) # Horizontal stack

array([[1, 2, 5],
       [3, 4, 6]])

## Exercise 4

### 1. Create a 6x6 matrix and reshape it into a 3D array of shape (3,2,2).

In [106]:
matrix_6x6 = np.arange(1, 37).reshape(6, 6)

reshaped_3d = matrix_6x6.reshape(3, 2, 6)

print("6x6 Matrix:\n", matrix_6x6)
print("\nReshaped 3D Array (3,2,6):\n", reshaped_3d)

6x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Reshaped 3D Array (3,2,6):
 [[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]]


### 2. Concatenate two arrays horizontally and vertically.

In [108]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

horizontal_concat = np.hstack((array1, array2))

print("Horizontally Concatenated Array:\n", horizontal_concat)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

vertical_concat = np.vstack((array1, array2))

print("\nVertically Concatenated Array:\n", vertical_concat)

Horizontally Concatenated Array:
 [[1 2 5 6]
 [3 4 7 8]]

Vertically Concatenated Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Homework 4

### Write a function that reshapes a given NumPy array into a square matrix if possible.

In [110]:
def reshape_to_square(arr):
    size = arr.size
    sqrt_size = int(np.sqrt(size))  # Calculate square root
    if sqrt_size ** 2 == size:  # Check if it's a perfect square
        return arr.reshape(sqrt_size, sqrt_size)
    else:
        raise ValueError("Array cannot be reshaped into a square matrix.")

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

try:
    square_matrix = reshape_to_square(array)
    print("Reshaped Square Matrix:\n", square_matrix)
except ValueError as e:
    print(e)

Reshaped Square Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Implement a script that joins two arrays along both axes and prints the result.

In [112]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

horizontal_join = np.hstack((array1, array2))  # Horizontal join (column-wise)
vertical_join = np.vstack((array1, array2))    # Vertical join (row-wise)

print("Horizontally Joined Array:\n", horizontal_join)
print("\nVertically Joined Array:\n", vertical_join)

Horizontally Joined Array:
 [[1 2 5 6]
 [3 4 7 8]]

Vertically Joined Array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Mathematical Operations

In [115]:
arr = np.array([1, 2, 3, 4])
print(arr + 5)  # Adds 5 to each element
print(arr * 2)  # Multiplies each element by 2

[6 7 8 9]
[2 4 6 8]


## Aggregation Functions

In [118]:
arr = np.array([5, 10, 15, 20])
print(arr.sum())  # Sum of all elements
print(arr.mean()) # Mean value
print(arr.max())  # Maximum value

50
12.5
20


## Exercise 5

### 1. Compute the sum, mean, max, and min of a 1D NumPy array.

In [124]:
array = np.array([10, 20, 30, 40, 50])

array_sum = np.sum(array)
array_mean = np.mean(array)
array_max = np.max(array)
array_min = np.min(array)

print("Array:", array)
print("Sum:", array_sum)
print("Mean:", array_mean)
print("Max:", array_max)
print("Min:", array_min)

Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Max: 50
Min: 10


### 2. Multiply two matrices using NumPy.

In [126]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result_matrix = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nResultant Matrix (Multiplication):\n", result_matrix)

Matrix 1:
 [[1 2]
 [3 4]]

Matrix 2:
 [[5 6]
 [7 8]]

Resultant Matrix (Multiplication):
 [[19 22]
 [43 50]]


## Homework 5

### Write a function that normalizes a NumPy array (scales values between 0 and 1).

In [132]:
def normalize_array(arr):
    min_val = np.min(arr)
    max_val = np.max(arr)
    return (arr - min_val) / (max_val - min_val) if max_val != min_val else arr

array = np.array([10, 20, 30, 40, 50])
normalized_array = normalize_array(array)

print("Original Array:", array)
print("Normalized Array:", normalized_array)

Original Array: [10 20 30 40 50]
Normalized Array: [0.   0.25 0.5  0.75 1.  ]


### Implement a script that calculates the dot product and cross product of two vectors.

In [134]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

dot_product = np.dot(vector1, vector2)

cross_product = np.cross(vector1, vector2)

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Dot Product:", dot_product)
print("Cross Product:", cross_product)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Dot Product: 32
Cross Product: [-3  6 -3]
