# UNIVERSAL FUNCTIONS OF NUMPY

## Addition
* The add() function adds the values of one array with the values of another array and returns a new array.

In [1]:
import numpy as np

Arr1 = np.array([10,20,30,40])
Arr2 = np.array([50,60,70,80])
New_Arr = np.add(Arr1,Arr2)

display(New_Arr)

array([ 60,  80, 100, 120])

## Subtraction
* The subtract() function subtracts the values of one array with the values of another array and returns a new array.

In [2]:
import numpy as np

Arr1 = np.array([10,20,30,40])
Arr2 = np.array([12,15,22,33])
New_Arr = np.subtract(Arr1,Arr2)

display(New_Arr)

array([-2,  5,  8,  7])

## Multiplication
* The multiply() function multiplies the values of one array with the values of another array.

In [3]:
import numpy as np

Arr1 = np.array([11,21,31,41])
Arr2 = np.array([55,66,77,88])
New_Arr = np.multiply(Arr1,Arr2)

display(New_Arr)

array([ 605, 1386, 2387, 3608])

## Division
* The divide() function divides the values of one array from the values of another array.

In [4]:
import numpy as np

Arr1 = np.array([10,20,30,40])
Arr2 = np.array([2,3,5,7])
New_Arr = np.divide(Arr1,Arr2)

display(New_Arr)

array([5.        , 6.66666667, 6.        , 5.71428571])

## Power
* The power() function rises the values of an array to the power of the values of another array.

In [5]:
import numpy as np

Arr1 = np.array([5,10,15,20])
Arr2 = np.array([3,4,5,6])
New_Arr = np.power(Arr1,Arr2)

display(New_Arr)

array([     125,    10000,   759375, 64000000], dtype=int32)

## Quotient And Remainder
* The divmod() function returns two arrays, the first array contains the quotient and the second array contains the remainder.

In [6]:
import numpy as np

Arr1 = np.array([20,40,60,80])
Arr2 = np.array([3,5,7,9])
New_Arr = np.divmod(Arr1,Arr2)

display(New_Arr)

(array([6, 8, 8, 8], dtype=int32), array([2, 0, 4, 8], dtype=int32))

## Truncation
* The trunc() function removes the decimal and returns the float value in a new array.

In [7]:
import numpy as np

Arr = np.trunc([4.226, -5.667, 7.436, -3.668])

display(Arr)

array([ 4., -5.,  7., -3.])

## Summations
* The sum() function sums the values of both the arrays. It happens over n elements.

In [8]:
import numpy as np

Arr1 = np.array([1,2,3,4])
Arr2 = np.array([10,20,30,40])
Arr3 = np.array([100,200,300,400])
New_Arr = np.sum([Arr1, Arr2, Arr3])

display(New_Arr)

1110

## Cummulative Sum
* The cumsum() function add elements partially in an array.

In [9]:
import numpy as np

Arr = np.array([11,21,31,41,51])
New_Arr = np.cumsum(Arr)

display(New_Arr)

array([ 11,  32,  63, 104, 155], dtype=int32)

## Products
* The prod() function multiplies all the elements of arrays.

In [10]:
import numpy as np

Arr1 = np.array([1,2,3,4])
Arr2 = np.array([10,20,30,40])
New_Arr = np.prod([Arr1, Arr2])

display(New_Arr)

5760000

## Cummulative Product
* The cumprod() function calculate the product of arrays partially. 

In [11]:
import numpy as np

Arr = np.array([1,5,10,15,20,25])
New_Arr = np.cumprod(Arr)

display(New_Arr)

array([     1,      5,     50,    750,  15000, 375000], dtype=int32)

## Differences
* The diff() function subtracts two successive elements.

In [12]:
import numpy as np

Arr = np.array([10,20,40,55,25])
New_Arr = np.diff(Arr)

display(New_Arr)

array([ 10,  20,  15, -30])

## Lowest Common Multiple(LCM)
* The lcm.reduce() function finds the lowest common multiple of all values in an array.

In [13]:
import numpy as np

Arr = np.array([1,3,6,9])
New_Arr = np.lcm.reduce(Arr)

display(New_Arr)

18

## Greatest Common Denominator(GCD)
* The gcd.reduce() function finds the highest common factor of all values in an array.

In [14]:
import numpy as np

Arr = np.array([8,20, 40, 16,])
New_Arr = np.gcd.reduce(Arr)

display(New_Arr)

4

## Sine
* The sin() function take values in radians and produce the corresponding sine values.

In [15]:
import numpy as np

Arr = np.array([np.pi/3, np.pi/5, np.pi/7, np.pi/2])
New_Arr = np.sin(Arr)

display(New_Arr)

array([0.8660254 , 0.58778525, 0.43388374, 1.        ])

## Hypotenues
* The hypot() function takes the base and perpendicular values and produces hypotenues based values using pythagoras theorem.

In [16]:
import numpy as np

Base = 5
Perpendicular = 10

Array = np.hypot(Base, Perpendicular)

display(Array)

11.180339887498949

## Hyperbolic Sine
* The sinh() function take values in radians and produce corresponding hyperbolic sine values.

In [17]:
import numpy as np

Array = np.array([np.pi/2, np.pi/4, np.pi/6, np.pi/8])
New_Arr = np.sinh(Array)

display(New_Arr)

array([2.3012989 , 0.86867096, 0.54785347, 0.40287038])

## Sets
* The unique() method finds the unique elements in an array and create a set array. Set arrays should only be 1-D arrays.

In [18]:
import numpy as np

Array = np.array([1,3,5,6,2,1,7,9,5,0,1,3])
New_Arr = np.unique(Array)

display(New_Arr)

array([0, 1, 2, 3, 5, 6, 7, 9])

## Union
* The union1d() function finds the unique values of two arrays.

In [19]:
import numpy as np

Arr1 = np.array([11,12,13,14])
Arr2 = np.array([15,12,16,14])
New_Arr = np.union1d(Arr1, Arr2)

display(New_Arr)

array([11, 12, 13, 14, 15, 16])

## Intersection
* The intersect1d() function finds the common values of both arrays.

In [20]:
import numpy as np

Arr1 = np.array([11,12,13,14])
Arr2 = np.array([15,12,16,14])
New_Arr = np.intersect1d(Arr1, Arr2, assume_unique = True)

display(New_Arr)

array([12, 14])